version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: bankmore_postgres
    restart: always
    environment:
      POSTGRES_DB: bankmoredb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MinhaSenha123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/create.sql:/docker-entrypoint-initdb.d/create.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bankmoredb"]
      interval: 5s
      timeout: 5s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: bankmore_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: bankmore_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  bankmore.api:
    build:
      context: .
      dockerfile: src/BankMore.Auth.API/Dockerfile
    container_name: bankmore_api
    environment:
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__PostgreSql=Host=postgres;Port=5432;Database=bankmoredb;Username=postgres;Password=MinhaSenha123;
      - JwtSettings__SecretKey=minha-chave-super-secreta-para-bankmore-1234567890
      - JwtSettings__Issuer=BankMore.Issuer
      - JwtSettings__Audience=BankMore.Audience
      - JwtSettings__ExpiresInMinutes=60
      - Kafka__BootstrapServers=kafka:9092
    ports:
      - "5000:80"
    depends_on:
      postgres:
        condition: service_healthy

  bankmore.web:
    build:
      context: .
      dockerfile: src/BankMore.Web/Dockerfile
    container_name: bankmore_web
    environment:
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ApiBaseUrl=http://bankmore_api:80
    ports:
      - "5001:80"
    depends_on:
      - bankmore.api

volumes:
  postgres_data:
