// <auto-generated />
using System;
using BankMore.Auth.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankMore.Auth.Infrastructure.Migrations
{
    [DbContext(typeof(BankMoreDbContext))]
    [Migration("20260824022053_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BankMore.Auth.Domain.Entities.ContaCorrente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idcontacorrente");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("atualizadoEm");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("criadoEm");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nome");

                    b.Property<int>("Numero")
                        .HasColumnType("int")
                        .HasColumnName("numero");

                    b.Property<decimal>("Saldo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("saldo");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("salt");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("senha");

                    b.HasKey("Id")
                        .HasName("PK_ContaCorrente");

                    b.ToTable("contacorrente", (string)null);
                });

            modelBuilder.Entity("BankMore.Auth.Domain.Entities.Idempotencia", b =>
                {
                    b.Property<string>("Chave")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("chave_idempotencia");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("criadoEm");

                    b.Property<string>("Requisicao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("requisicao");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("resultado");

                    b.HasKey("Chave")
                        .HasName("PK_Idempotencia");

                    b.ToTable("idempotencia", (string)null);
                });

            modelBuilder.Entity("BankMore.Auth.Domain.Entities.Movimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idmovimento");

                    b.Property<string>("ChaveIdempotencia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("chave_idempotencia");

                    b.Property<DateTime>("DataMovimento")
                        .HasColumnType("datetime2")
                        .HasColumnName("datamovimento");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("descricao");

                    b.Property<Guid>("IdContaCorrente")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idcontacorrente");

                    b.Property<string>("TipoMovimento")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("tipomovimento");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("PK_Movimento");

                    b.HasIndex("ChaveIdempotencia")
                        .IsUnique()
                        .HasDatabaseName("idx_movimento_idempotencia");

                    b.HasIndex("DataMovimento")
                        .HasDatabaseName("idx_movimento_data");

                    b.HasIndex("IdContaCorrente")
                        .HasDatabaseName("idx_movimento_conta");

                    b.ToTable("movimento", (string)null);
                });

            modelBuilder.Entity("BankMore.Auth.Domain.Entities.Transferencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idtransferencia");

                    b.Property<DateTime>("DataMovimento")
                        .HasColumnType("datetime2")
                        .HasColumnName("datamovimento");

                    b.Property<Guid>("IdContaDestino")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idcontadestino");

                    b.Property<Guid>("IdContaOrigem")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idcontaorigem");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("PK_Transferencia");

                    b.HasIndex("IdContaDestino")
                        .HasDatabaseName("idx_transferencia_destino");

                    b.HasIndex("IdContaOrigem")
                        .HasDatabaseName("idx_transferencia_origem");

                    b.ToTable("transferencia", (string)null);
                });

            modelBuilder.Entity("BankMore.Auth.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("criadoEm");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("senhaHash");

                    b.HasKey("Id")
                        .HasName("PK_Usuarios");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("idx_usuarios_cpf");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("idx_usuarios_email");

                    b.ToTable("usuarios", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
